AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  storysam

  Sample SAM Template for storysam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15
    MemorySize: 128
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  GenerateStoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: generate_story/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Policies: 
        - AWSLambdaBasicExecutionRole
        - DynamoDBWritePolicy:
            TableName: 'stories'
        - SSMParameterReadPolicy:
            ParameterName: 'storysam/*'
      Events:
        StoryApi:
          Type: HttpApi 
          Properties:
            Path: /story
            Method: post
  ListStoriesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: list_stories/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Policies: 
        - AWSLambdaBasicExecutionRole
        - DynamoDBReadPolicy:
            TableName: 'stories'
        - SSMParameterReadPolicy:
            ParameterName: 'storysam/*'
      Events:
        StoryApi:
          Type: HttpApi 
          Properties:
            Path: /stories
            Method: get                      
  GetStoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_story/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Policies: 
        - AWSLambdaBasicExecutionRole
        - DynamoDBReadPolicy:
            TableName: 'stories'
        - SSMParameterReadPolicy:
            ParameterName: 'storysam/*'
      Events:
        StoryApi:
          Type: HttpApi 
          Properties:
            Path: /story/{id}
            Method: get          
  StoriesTable:
    Type: AWS::DynamoDB::Table
    Properties:
        TableName: stories
        AttributeDefinitions:
            - AttributeName: id
              AttributeType: S
        KeySchema:
            - AttributeName: id
              KeyType: HASH
        ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      AutoConfigurationEnabled: 'true'
    DependsOn: ApplicationResourceGroup
Outputs:
    StoryApi:
        Description: API Gateway endpoint URL for Prod stage for Hello World function
        Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/story"

